navbar:
  blog_title: 狼的站点
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }
    - { key: 'project', link: '/project/', name: '项目' }
    - { key: 'tools', link: '/tools/', name: '工具' }
    - { key: 'donate', link: '/donate/', name: '捐赠' }
    # - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
  ground_glass:
    enable: true

web_analytics:
  enable: true
  gtag: G-2QFHFRZW64

footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

about:
  avatar: /images/face.png
  name: "狼(o0kam1)"
  intro: "大概是废物"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/duzhaokun123', tip: 'github' }
    - { class: 'iconfont icon-twitter-fill', link: 'https://twitter.com/duzhaokun123', tip: 'twitter'}
    - { class: 'iconfont icon-bilibili-fill', link: 'https://space.bilibili.com/174438027', tip: '哔哩哔哩'}
    - { class: 'iconfont icon-stack-overflow-fill', link: 'https://stackoverflow.com/users/12194913/duzhaokun123', tip: 'stackoverflow'}
    - { class: 'iconfont icon-zhihu-fill', link: 'https://www.zhihu.com/people/du-zhao-kun-92', tip: '知乎'}
    - { class: 'iconfont icon-telegram-fill', link: 'https://space.bilibili.com/174438027', tip: 'bilibili'}
    

links:
  items:
    - {
      title: 'Fluid Docs',
      intro: '主题使用指南',
      link: 'https://hexo.fluid-dev.com/docs/',
      avatar: '/img/favicon.png'
    }

favicon: favicon.ico
apple_touch_icon: favicon.ico
tab_title_separator: ' | '
force_https: true

index:
  slogan:
    text: "狼的 记录并没有什么用的东西的 站点"