navbar:
  blog_title: 狼的站点
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }
    - { key: 'project', link: '/project/', name: '项目' }
    - { key: 'tools', link: '/tools/', name: '工具' }
    - { key: 'donate', link: '/donate/', name: '捐赠' }
    # - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
  ground_glass:
    enable: true

web_analytics:
  enable: true
  gtag: G-2QFHFRZW64

footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

about:
  avatar: /images/avatar.png
  name: "狼(o0kam1)"
  intro: "大概是废物"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/duzhaokun123', tip: 'github' }
    - { class: 'iconfont icon-twitter-fill', link: 'https://twitter.com/duzhaokun123', tip: 'twitter'}
    - { class: 'iconfont icon-bilibili-fill', link: 'https://space.bilibili.com/174438027', tip: '哔哩哔哩'}
    - { class: 'iconfont icon-stack-overflow-fill', link: 'https://stackoverflow.com/users/12194913/duzhaokun123', tip: 'stackoverflow'}
    - { class: 'iconfont icon-zhihu-fill', link: 'https://www.zhihu.com/people/du-zhao-kun-92', tip: '知乎'}
    - { class: 'iconfont icon-telegram-fill', link: 'https://space.bilibili.com/174438027', tip: 'bilibili'}
    

links:
  title: '朋友们(部分)'
  subtitle: '朋友们(部分)
  按字典顺序排序'
  banner_img_height: 40
  banner_mask_alpha: 0.5
  items:
    - {
      title: 'Chi_Tang',
      intro: '只是一个普通的初中生罢了',
      link: 'https://blog.chitang.dev/',
      avatar: 'https://chitangcos.zyglq.cn/images/avatar.webp'
    }
    - {
      title: 'KimmyXYC',
      intro: '嗯？谁在那里？',
      link: 'https://www.kimmyxyc.top/',
      avatar: 'https://kimcos.zyglq.cn/img/2023/01/05/11-10-28-c9d465352d7e7064b126ebe4576c5de8.jpg'
    }
    - {
      title: 'Molyuu',
      intro: 'Molyuu Blog',
      link: 'https://blog.molyuu.xyz/',
      avatar: 'https://cos.zyglq.cn/static/link-pic/230129.molyuu.xyz.jpg' 
    }
    - {
      title: 'Purofle',
      intro: 'Purofle的Blog',
      link: 'https://blog.archlinux.tech/',
      avatar: 'https://cos.zyglq.cn/static/link-pic/230124.archlinux.tech.png'
    }
    - {
      title: '笨蛋ovo',
      intro: '笨蛋小破站',
      link: 'https://bdovo.cc/',
      avatar: 'https://obdo.cc/icon'
    }
    - {
      title: '残页',
      intro: '残页的小博客',
      link: 'https://blog.canyie.top/',
      avatar: 'https://blog.canyie.top/data/image/avatar_round_new.png'
    }
#    - {
#      title: '是一刀斩哒♡',
#      intro: '一刀斩の小窝',
#      link: 'https://blog.yidaozhan.top/',
#      avatar: 'https://cos.zyglq.cn/static/link-pic/230124.yidaozhan.top.jfif'
#    }
    - {
        title: '千雪',
        intro: '千雪的咖啡厅',
        link: 'https://chyk.ink/',
        avatar: 'https://q1.qlogo.cn/g?b=qq&nk=3526514925&s=640'
    }
    - {
      title: '易然',
      intro: '易然的猫窝~',
      link: 'https://web.archive.org/web/20230000000000*/https://%E6%98%93%E7%84%B6.xyz',
      avatar: 'https://cos.zyglq.cn/static/link-pic/230220.yiran.xyz.jpg'
    }
    - {
      title: '资源管理器博客',
      intro: '心中有光，对立重伤',
      link: 'https://www.zyglq.cn/',
      avatar: 'https://cos.zyglq.cn/static/web-logo.jpg'
    }

favicon: favicon.ico
apple_touch_icon: favicon.ico
tab_title_separator: ' | '
force_https: true

index:
  slogan:
    text: "狼的 记录并没有什么用的东西的 站点"

code:
  highlight:
    highlightjs:
      style: "github"
      style_dark: "github-dark"

post:
  copyright:
    license: 'BY-SA'
  prev_next:
    enable: false